language: php
sudo: enabled

services:
  - mysql

addons:
  chrome: stable

git:
  depth: 3

php:
  - '5.6'
  - '7.0'
  - '7.1'

env:
  global:
    - HUMHUB_PATH=/opt/humhub
#  matrix:
#    - HUMHUB_VERSION=master
#    - HUMHUB_VERSION=v1.3-dev

cache:
  directories:
    - $HOME/.composer/cache

install:
  - /bin/sh .travis/install-dependencies.sh
  - /bin/sh .travis/setup-humhub.sh

script:
  - cd tests
  - php ${HUMHUB_PATH}/protected/vendor/bin/codecept build
  - php ${HUMHUB_PATH}/protected/vendor/bin/codecept run
