name: PHP Codeception Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests-v1.10.yml@main
    with:
      module-id: calendar
      use-rest-module: true
      install-composer: true